spring.application.name=LendBuddy
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:C:/Users/verma/OneDrive/Desktop/spring/db
spring.datasource.username=tejas
spring.datasource.password=Tejas@123
spring.jpa.hibernate.ddl-auto=create
jwt.secretKey=H8GfdL9n+hsZWDnP8h4+uAjhAh4TS5jGIKq3i0RxPXk=
